# Generated by Django 5.1 on 2024-10-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30, verbose_name='FirstName')),
                ('LastName', models.CharField(max_length=30, verbose_name='LastName')),
                ('Password', models.CharField(max_length=30, verbose_name='Password')),
                ('Email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('Birthday', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
