# Generated by Django 5.1 on 2024-10-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenkaiZoneRailImpact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='ContactNo',
            field=models.CharField(max_length=11, null=True, verbose_name='ContactNo.'),
        ),
    ]
