# Generated by Django 5.1 on 2024-10-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenkaiZoneRailImpact', '0003_accounts_sec_answer_accounts_sec_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Sec_Pin',
            field=models.CharField(max_length=4, null=True, verbose_name='Security PIN'),
        ),
    ]
