# Generated by Django 5.1 on 2024-10-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenkaiZoneRailImpact', '0005_foodcatalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcatalog',
            name='FoodCategory',
            field=models.CharField(max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='foodcatalog',
            name='FoodPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
