# Generated by Django 5.1 on 2024-10-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenkaiZoneRailImpact', '0008_alter_accounts_contactno_alter_foodcatalog_dateadded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temptransaction',
            old_name='FoodID',
            new_name='Food',
        ),
    ]
