# Generated by Django 5.1.1 on 2025-01-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenkaiZoneRailImpact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
