# Generated by Django 5.1 on 2024-10-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenkaiZoneRailImpact', '0002_accounts_contactno'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='Sec_Answer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Security Answer'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='Sec_Pin',
            field=models.CharField(max_length=6, null=True, verbose_name='Security PIN'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='Sec_Question',
            field=models.CharField(max_length=200, null=True, verbose_name='SecurityQuestion'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='Wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Wallet'),
        ),
    ]
