# Generated by Django 5.1 on 2024-10-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenkaiZoneRailImpact', '0006_alter_foodcatalog_foodcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcatalog',
            name='FoodCategory',
            field=models.CharField(max_length=30, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='foodcatalog',
            name='FoodRating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='foodcatalog',
            name='FoodViews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
