# Generated by Django 5.1 on 2024-10-21 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenkaiZoneRailImpact', '0007_alter_foodcatalog_foodcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='ContactNo',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='ContactNo.'),
        ),
        migrations.AlterField(
            model_name='foodcatalog',
            name='DateAdded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foodcatalog',
            name='FoodCategory',
            field=models.CharField(max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='foodcatalog',
            name='FoodName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='TempTransaction',
            fields=[
                ('TempTransactID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=1)),
                ('TransactionDate', models.DateTimeField(auto_now_add=True)),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenkaiZoneRailImpact.foodcatalog')),
            ],
        ),
    ]
