# Generated by Django 5.1 on 2024-10-27 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenkaiZoneRailImpact', '0010_accounts_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('CheckoutID', models.AutoField(primary_key=True, serialize=False)),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='temptransaction',
            name='Food',
        ),
        migrations.RemoveField(
            model_name='temptransaction',
            name='Quantity',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartID', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenkaiZoneRailImpact.temptransaction')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOfPurchase',
            fields=[
                ('Checkout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GenkaiZoneRailImpact.checkout')),
                ('DateCompleted', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='Cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenkaiZoneRailImpact.cart'),
        ),
        migrations.CreateModel(
            name='TempTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenkaiZoneRailImpact.foodcatalog')),
                ('TempTransaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenkaiZoneRailImpact.temptransaction')),
            ],
        ),
        migrations.AddField(
            model_name='temptransaction',
            name='FoodItems',
            field=models.ManyToManyField(through='GenkaiZoneRailImpact.TempTransactionItem', to='GenkaiZoneRailImpact.foodcatalog'),
        ),
        migrations.CreateModel(
            name='Void',
            fields=[
                ('VoidID', models.AutoField(primary_key=True, serialize=False)),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('Checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenkaiZoneRailImpact.checkout')),
            ],
        ),
    ]
