# Generated by Django 5.1 on 2024-11-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenkaiZoneRailImpact', '0011_checkout_remove_temptransaction_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='Barangay',
            field=models.CharField(max_length=100, null=True, verbose_name='Barangay'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='BlockLot',
            field=models.CharField(max_length=100, null=True, verbose_name='Block & Lot'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='City',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='Province',
            field=models.CharField(max_length=100, null=True, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='Street',
            field=models.CharField(max_length=100, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='Subdivision',
            field=models.CharField(max_length=100, null=True, verbose_name='Subdivision'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='ContactNo',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='Contact No.'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='FirstName',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='LastName',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='Sec_Question',
            field=models.CharField(max_length=200, null=True, verbose_name='Security Question'),
        ),
    ]
